steps:

# - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
#   entrypoint: 'bash'
#   args:
#   - '-c'
#   - |
#     echo "Authenticating Docker with Artifact Registry..."
#     gcloud auth configure-docker ${_ARTIFACT_REGION}-docker.pkg.dev

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_ARTIFACT_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_NAME}/${_IMAGE_NAME}:latest', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_ARTIFACT_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_NAME}/${_IMAGE_NAME}:latest']

images:
- '${_ARTIFACT_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_NAME}/${_IMAGE_NAME}:latest'
